<?php
require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

// Delete old organizing committee
DB::table('committee_members')->where('category', 'organizing_committee')->delete();

$members = [
    [
        'name' => 'Dr. V. Mahalakshmi',
        'designation' => 'Head & Associate Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 1,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. S. Niren Andrew',
        'designation' => 'Assistant Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 2,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. K. Kavitha',
        'designation' => 'Associate Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 3,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. S. Premina',
        'designation' => 'Assistant Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 4,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. S. Abirami',
        'designation' => 'Assistant Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 5,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. P. Hanumantha Rao',
        'designation' => 'Associate Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 6,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. T. Sathish Kumar',
        'designation' => 'Associate Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 7,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. V. Vedha',
        'designation' => 'Assistant Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 8,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. K. Balakumar',
        'designation' => 'Assistant Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 9,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. Neginah Vijayasingh J',
        'designation' => 'Assistant Professor, Department of Microbiology',
        'category' => 'organizing_committee',
        'subcategory' => 'microbiology',
        'sort_order' => 10,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. S. Sahila',
        'designation' => 'Assistant Professor, Department of Chemistry',
        'category' => 'organizing_committee',
        'subcategory' => 'other',
        'sort_order' => 11,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. S. Daniel Abraham',
        'designation' => 'Assistant Professor, Department of Chemistry',
        'category' => 'organizing_committee',
        'subcategory' => 'other',
        'sort_order' => 12,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. K. Vijayalakshmi',
        'designation' => 'Assistant Professor, Department of Chemistry',
        'category' => 'organizing_committee',
        'subcategory' => 'other',
        'sort_order' => 13,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. A. Bebin',
        'designation' => 'Assistant Professor, Department of Chemistry',
        'category' => 'organizing_committee',
        'subcategory' => 'other',
        'sort_order' => 14,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. Vijay Solomon',
        'designation' => 'Associate Dean, RnD',
        'category' => 'organizing_committee',
        'subcategory' => 'other',
        'sort_order' => 15,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. S. Kalyani',
        'designation' => 'Associate Dean, RnD',
        'category' => 'organizing_committee',
        'subcategory' => 'other',
        'sort_order' => 16,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. U. Senthilkumar',
        'designation' => 'Assistant Professor, Dept. of Botany',
        'category' => 'organizing_committee',
        'subcategory' => 'other',
        'sort_order' => 17,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dr. Anulin Christudas',
        'designation' => 'Assistant Professor, Dept. of Zoology',
        'category' => 'organizing_committee',
        'subcategory' => 'other',
        'sort_order' => 18,
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ]
];

DB::table('committee_members')->insert($members);
echo "Updated Organizing Committee successfully.\n";
